// Code generated by go generate; DO NOT EDIT.
package data

import "time"

var Exercises = map[string]Exercise{
	"Bridges": Exercise{
		Name: "Bridges",
		Steps: []Step{
			Step{
				Name: "Short Bridges",
				Goals: []Goal{
					Goal{ 1, 10, time.Duration(0) }, // "0s"
					Goal{ 2, 25, time.Duration(0) }, // "0s"
					Goal{ 3, 50, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "Straight Bridges",
				Goals: []Goal{
					Goal{ 1, 10, time.Duration(0) }, // "0s"
					Goal{ 2, 20, time.Duration(0) }, // "0s"
					Goal{ 3, 40, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "Angled Bridges",
				Goals: []Goal{
					Goal{ 1, 8, time.Duration(0) }, // "0s"
					Goal{ 2, 15, time.Duration(0) }, // "0s"
					Goal{ 3, 30, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "Head Bridges",
				Goals: []Goal{
					Goal{ 1, 8, time.Duration(0) }, // "0s"
					Goal{ 2, 15, time.Duration(0) }, // "0s"
					Goal{ 2, 25, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "Half Bridges",
				Goals: []Goal{
					Goal{ 1, 8, time.Duration(0) }, // "0s"
					Goal{ 2, 15, time.Duration(0) }, // "0s"
					Goal{ 2, 20, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "Full Bridges",
				Goals: []Goal{
					Goal{ 1, 6, time.Duration(0) }, // "0s"
					Goal{ 2, 10, time.Duration(0) }, // "0s"
					Goal{ 2, 15, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "Wall Walking Bridges (Down)",
				Goals: []Goal{
					Goal{ 1, 3, time.Duration(0) }, // "0s"
					Goal{ 2, 6, time.Duration(0) }, // "0s"
					Goal{ 2, 10, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "Wall Walking Bridges (Up)",
				Goals: []Goal{
					Goal{ 1, 2, time.Duration(0) }, // "0s"
					Goal{ 2, 4, time.Duration(0) }, // "0s"
					Goal{ 2, 8, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "Closing Bridges",
				Goals: []Goal{
					Goal{ 1, 1, time.Duration(0) }, // "0s"
					Goal{ 2, 3, time.Duration(0) }, // "0s"
					Goal{ 2, 6, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "Stand-To-Stand Bridges",
				Goals: []Goal{
					Goal{ 1, 1, time.Duration(0) }, // "0s"
					Goal{ 2, 3, time.Duration(0) }, // "0s"
					Goal{ 2, 30, time.Duration(0) }, // "0s"
				},
			},
		},
	},
	"Handstand Pushups": Exercise{
		Name: "Handstand Pushups",
		Steps: []Step{
			Step{
				Name: "Wall Headstands",
				Goals: []Goal{
					Goal{ 1, 0, time.Duration(30000000000) }, // "30s"
					Goal{ 1, 0, time.Duration(60000000000) }, // "1m0s"
					Goal{ 1, 0, time.Duration(120000000000) }, // "2m0s"
				},
			},
			Step{
				Name: "Crow Stands",
				Goals: []Goal{
					Goal{ 1, 0, time.Duration(10000000000) }, // "10s"
					Goal{ 1, 0, time.Duration(30000000000) }, // "30s"
					Goal{ 1, 0, time.Duration(60000000000) }, // "1m0s"
				},
			},
			Step{
				Name: "Wall Handstands",
				Goals: []Goal{
					Goal{ 1, 0, time.Duration(30000000000) }, // "30s"
					Goal{ 1, 0, time.Duration(60000000000) }, // "1m0s"
					Goal{ 1, 0, time.Duration(120000000000) }, // "2m0s"
				},
			},
			Step{
				Name: "Half Handstand Pushups",
				Goals: []Goal{
					Goal{ 1, 5, time.Duration(0) }, // "0s"
					Goal{ 2, 10, time.Duration(0) }, // "0s"
					Goal{ 2, 20, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "Handstand Pushups",
				Goals: []Goal{
					Goal{ 1, 5, time.Duration(0) }, // "0s"
					Goal{ 2, 10, time.Duration(0) }, // "0s"
					Goal{ 2, 15, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "Close Handstand Pushups",
				Goals: []Goal{
					Goal{ 1, 5, time.Duration(0) }, // "0s"
					Goal{ 2, 9, time.Duration(0) }, // "0s"
					Goal{ 2, 12, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "Uneven Handstand Pushups",
				Goals: []Goal{
					Goal{ 1, 5, time.Duration(0) }, // "0s"
					Goal{ 2, 8, time.Duration(0) }, // "0s"
					Goal{ 2, 10, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "1/2 One-Arm Handstand Pushups",
				Goals: []Goal{
					Goal{ 1, 4, time.Duration(0) }, // "0s"
					Goal{ 2, 6, time.Duration(0) }, // "0s"
					Goal{ 2, 8, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "Lever Handstand Pushups",
				Goals: []Goal{
					Goal{ 1, 3, time.Duration(0) }, // "0s"
					Goal{ 2, 4, time.Duration(0) }, // "0s"
					Goal{ 2, 6, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "One-Arm Handstand Pushups",
				Goals: []Goal{
					Goal{ 1, 1, time.Duration(0) }, // "0s"
					Goal{ 2, 2, time.Duration(0) }, // "0s"
					Goal{ 1, 5, time.Duration(0) }, // "0s"
				},
			},
		},
	},
	"Leg Raises": Exercise{
		Name: "Leg Raises",
		Steps: []Step{
			Step{
				Name: "Knee Tucks",
				Goals: []Goal{
					Goal{ 1, 10, time.Duration(0) }, // "0s"
					Goal{ 2, 25, time.Duration(0) }, // "0s"
					Goal{ 3, 40, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "Flat Knee Raises",
				Goals: []Goal{
					Goal{ 1, 10, time.Duration(0) }, // "0s"
					Goal{ 2, 20, time.Duration(0) }, // "0s"
					Goal{ 3, 35, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "Flat Bent Leg Raises",
				Goals: []Goal{
					Goal{ 1, 10, time.Duration(0) }, // "0s"
					Goal{ 2, 15, time.Duration(0) }, // "0s"
					Goal{ 3, 30, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "Flat Frog Raises",
				Goals: []Goal{
					Goal{ 1, 8, time.Duration(0) }, // "0s"
					Goal{ 2, 15, time.Duration(0) }, // "0s"
					Goal{ 3, 25, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "Flat Straight Leg Raises",
				Goals: []Goal{
					Goal{ 1, 5, time.Duration(0) }, // "0s"
					Goal{ 2, 10, time.Duration(0) }, // "0s"
					Goal{ 2, 20, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "Hanging Knee Raises",
				Goals: []Goal{
					Goal{ 1, 5, time.Duration(0) }, // "0s"
					Goal{ 2, 10, time.Duration(0) }, // "0s"
					Goal{ 2, 15, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "Hanging Bent Leg Raises",
				Goals: []Goal{
					Goal{ 1, 5, time.Duration(0) }, // "0s"
					Goal{ 2, 10, time.Duration(0) }, // "0s"
					Goal{ 2, 15, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "Hanging Frog Raises",
				Goals: []Goal{
					Goal{ 1, 5, time.Duration(0) }, // "0s"
					Goal{ 2, 10, time.Duration(0) }, // "0s"
					Goal{ 2, 15, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "Partial Straight Leg Raises",
				Goals: []Goal{
					Goal{ 1, 5, time.Duration(0) }, // "0s"
					Goal{ 2, 10, time.Duration(0) }, // "0s"
					Goal{ 2, 15, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "Hanging Straight Leg Raises",
				Goals: []Goal{
					Goal{ 1, 5, time.Duration(0) }, // "0s"
					Goal{ 2, 10, time.Duration(0) }, // "0s"
					Goal{ 2, 30, time.Duration(0) }, // "0s"
				},
			},
		},
	},
	"Pullups": Exercise{
		Name: "Pullups",
		Steps: []Step{
			Step{
				Name: "Vertical Pulls",
				Goals: []Goal{
					Goal{ 1, 10, time.Duration(0) }, // "0s"
					Goal{ 2, 20, time.Duration(0) }, // "0s"
					Goal{ 3, 40, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "Horizontal Pulls",
				Goals: []Goal{
					Goal{ 1, 10, time.Duration(0) }, // "0s"
					Goal{ 2, 20, time.Duration(0) }, // "0s"
					Goal{ 3, 30, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "Jackknife Pulls",
				Goals: []Goal{
					Goal{ 1, 10, time.Duration(0) }, // "0s"
					Goal{ 2, 15, time.Duration(0) }, // "0s"
					Goal{ 3, 20, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "Half Pullups",
				Goals: []Goal{
					Goal{ 1, 8, time.Duration(0) }, // "0s"
					Goal{ 2, 11, time.Duration(0) }, // "0s"
					Goal{ 2, 15, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "Full Pullups",
				Goals: []Goal{
					Goal{ 1, 5, time.Duration(0) }, // "0s"
					Goal{ 2, 8, time.Duration(0) }, // "0s"
					Goal{ 2, 10, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "Close Pullups",
				Goals: []Goal{
					Goal{ 1, 5, time.Duration(0) }, // "0s"
					Goal{ 2, 8, time.Duration(0) }, // "0s"
					Goal{ 2, 10, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "Uneven Pullups",
				Goals: []Goal{
					Goal{ 1, 5, time.Duration(0) }, // "0s"
					Goal{ 2, 7, time.Duration(0) }, // "0s"
					Goal{ 2, 9, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "1/2 One-Arm Pullups",
				Goals: []Goal{
					Goal{ 1, 4, time.Duration(0) }, // "0s"
					Goal{ 2, 6, time.Duration(0) }, // "0s"
					Goal{ 2, 8, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "Assisted One-Arm Pullups",
				Goals: []Goal{
					Goal{ 1, 3, time.Duration(0) }, // "0s"
					Goal{ 2, 5, time.Duration(0) }, // "0s"
					Goal{ 2, 7, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "One-Arm Pullups",
				Goals: []Goal{
					Goal{ 1, 1, time.Duration(0) }, // "0s"
					Goal{ 2, 3, time.Duration(0) }, // "0s"
					Goal{ 2, 6, time.Duration(0) }, // "0s"
				},
			},
		},
	},
	"Pushups": Exercise{
		Name: "Pushups",
		Steps: []Step{
			Step{
				Name: "Wall Pushups",
				Goals: []Goal{
					Goal{ 1, 10, time.Duration(0) }, // "0s"
					Goal{ 2, 25, time.Duration(0) }, // "0s"
					Goal{ 3, 50, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "Incline Pushups",
				Goals: []Goal{
					Goal{ 1, 10, time.Duration(0) }, // "0s"
					Goal{ 2, 20, time.Duration(0) }, // "0s"
					Goal{ 3, 40, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "Kneeling Pushups",
				Goals: []Goal{
					Goal{ 1, 10, time.Duration(0) }, // "0s"
					Goal{ 2, 15, time.Duration(0) }, // "0s"
					Goal{ 3, 30, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "Half Pushups",
				Goals: []Goal{
					Goal{ 1, 8, time.Duration(0) }, // "0s"
					Goal{ 2, 12, time.Duration(0) }, // "0s"
					Goal{ 3, 25, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "Full Pushups",
				Goals: []Goal{
					Goal{ 1, 5, time.Duration(0) }, // "0s"
					Goal{ 2, 10, time.Duration(0) }, // "0s"
					Goal{ 2, 20, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "Close Pushups",
				Goals: []Goal{
					Goal{ 1, 5, time.Duration(0) }, // "0s"
					Goal{ 2, 10, time.Duration(0) }, // "0s"
					Goal{ 2, 20, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "Uneven Pushups",
				Goals: []Goal{
					Goal{ 1, 5, time.Duration(0) }, // "0s"
					Goal{ 2, 10, time.Duration(0) }, // "0s"
					Goal{ 2, 20, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "1/2 One-Arm Pushups",
				Goals: []Goal{
					Goal{ 1, 5, time.Duration(0) }, // "0s"
					Goal{ 2, 10, time.Duration(0) }, // "0s"
					Goal{ 2, 20, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "Lever Pushups",
				Goals: []Goal{
					Goal{ 1, 5, time.Duration(0) }, // "0s"
					Goal{ 2, 10, time.Duration(0) }, // "0s"
					Goal{ 2, 20, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "One-Arm Pushups",
				Goals: []Goal{
					Goal{ 1, 5, time.Duration(0) }, // "0s"
					Goal{ 2, 10, time.Duration(0) }, // "0s"
					Goal{ 1, 100, time.Duration(0) }, // "0s"
				},
			},
		},
	},
	"Squats": Exercise{
		Name: "Squats",
		Steps: []Step{
			Step{
				Name: "Shoulderstand Squats",
				Goals: []Goal{
					Goal{ 1, 10, time.Duration(0) }, // "0s"
					Goal{ 2, 25, time.Duration(0) }, // "0s"
					Goal{ 3, 50, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "Jackknife Squats",
				Goals: []Goal{
					Goal{ 1, 10, time.Duration(0) }, // "0s"
					Goal{ 2, 20, time.Duration(0) }, // "0s"
					Goal{ 3, 40, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "Supported Squats",
				Goals: []Goal{
					Goal{ 1, 10, time.Duration(0) }, // "0s"
					Goal{ 2, 15, time.Duration(0) }, // "0s"
					Goal{ 3, 30, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "Half Squats",
				Goals: []Goal{
					Goal{ 1, 8, time.Duration(0) }, // "0s"
					Goal{ 2, 35, time.Duration(0) }, // "0s"
					Goal{ 2, 50, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "Full Squats",
				Goals: []Goal{
					Goal{ 1, 5, time.Duration(0) }, // "0s"
					Goal{ 2, 10, time.Duration(0) }, // "0s"
					Goal{ 2, 30, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "Close Squats",
				Goals: []Goal{
					Goal{ 1, 5, time.Duration(0) }, // "0s"
					Goal{ 2, 10, time.Duration(0) }, // "0s"
					Goal{ 2, 20, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "Uneven Squats",
				Goals: []Goal{
					Goal{ 1, 5, time.Duration(0) }, // "0s"
					Goal{ 2, 10, time.Duration(0) }, // "0s"
					Goal{ 2, 20, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "1/2 One-Leg Squats",
				Goals: []Goal{
					Goal{ 1, 5, time.Duration(0) }, // "0s"
					Goal{ 2, 10, time.Duration(0) }, // "0s"
					Goal{ 2, 20, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "Assisted One-Leg Squats",
				Goals: []Goal{
					Goal{ 1, 5, time.Duration(0) }, // "0s"
					Goal{ 2, 10, time.Duration(0) }, // "0s"
					Goal{ 2, 20, time.Duration(0) }, // "0s"
				},
			},
			Step{
				Name: "One-Leg Squats",
				Goals: []Goal{
					Goal{ 1, 5, time.Duration(0) }, // "0s"
					Goal{ 2, 10, time.Duration(0) }, // "0s"
					Goal{ 2, 50, time.Duration(0) }, // "0s"
				},
			},
		},
	},
}
