// Code generated by go generate; DO NOT EDIT.
package data

//*

var Plans = map[string]Plan{
	"Good Behaviour": Plan{
		Name: "Good Behaviour",
		Days: Days{
			"Friday": []Workout{
				Workout{
					Name: "Handstand Pushups",
					Sets: []int{
						2,
					},
				},
				Workout{
					Name: "Bridges",
					Sets: []int{
						2,
					},
				},
			},
			"Monday": []Workout{
				Workout{
					Name: "Pushups",
					Sets: []int{
						2,
					},
				},
				Workout{
					Name: "Leg Raises",
					Sets: []int{
						2,
					},
				},
			},
			"Saturday": []Workout{
			},
			"Sunday": []Workout{
			},
			"Thursday": []Workout{
			},
			"Tuesday": []Workout{
			},
			"Wednesday": []Workout{
				Workout{
					Name: "Pullups",
					Sets: []int{
						2,
					},
				},
				Workout{
					Name: "Squats",
					Sets: []int{
						2,
					},
				},
			},
		},
	},
	"New Blood": Plan{
		Name: "New Blood",
		Days: Days{
			"Friday": []Workout{
				Workout{
					Name: "Pullups",
					Sets: []int{
						2,
						3,
					},
				},
				Workout{
					Name: "Squats",
					Sets: []int{
						2,
						3,
					},
				},
			},
			"Monday": []Workout{
				Workout{
					Name: "Pushups",
					Sets: []int{
						2,
						3,
					},
				},
				Workout{
					Name: "Leg Raises",
					Sets: []int{
						2,
						3,
					},
				},
			},
			"Saturday": []Workout{
			},
			"Sunday": []Workout{
			},
			"Thursday": []Workout{
			},
			"Tuesday": []Workout{
			},
			"Wednesday": []Workout{
			},
		},
	},
	"Solitary Confinement": Plan{
		Name: "Solitary Confinement",
		Days: Days{
			"Friday": []Workout{
				Workout{
					Name: "Pushups",
					Sets: []int{
						3,
						5,
					},
				},
				Workout{
					Name: "Leg Raises",
					Sets: []int{
						3,
						5,
					},
				},
				Workout{
					Name: "Calf work",
					Sets: []int{
						3,
						5,
					},
				},
			},
			"Monday": []Workout{
				Workout{
					Name: "Pullups",
					Sets: []int{
						3,
						5,
					},
				},
				Workout{
					Name: "Squats",
					Sets: []int{
						3,
						5,
					},
				},
				Workout{
					Name: "Grip work",
					Sets: []int{
					},
				},
			},
			"Saturday": []Workout{
				Workout{
					Name: "Handstand Pushups",
					Sets: []int{
						3,
						5,
					},
				},
				Workout{
					Name: "Bridges",
					Sets: []int{
						3,
						5,
					},
				},
				Workout{
					Name: "Neck work",
					Sets: []int{
						2,
						4,
					},
				},
			},
			"Sunday": []Workout{
			},
			"Thursday": []Workout{
				Workout{
					Name: "Pullups",
					Sets: []int{
						3,
						5,
					},
				},
				Workout{
					Name: "Squats",
					Sets: []int{
						3,
						5,
					},
				},
				Workout{
					Name: "Grip work",
					Sets: []int{
					},
				},
			},
			"Tuesday": []Workout{
				Workout{
					Name: "Pushups",
					Sets: []int{
						3,
						5,
					},
				},
				Workout{
					Name: "Leg Raises",
					Sets: []int{
						3,
						5,
					},
				},
				Workout{
					Name: "Calf work",
					Sets: []int{
						3,
						5,
					},
				},
			},
			"Wednesday": []Workout{
				Workout{
					Name: "Handstand Pushups",
					Sets: []int{
						3,
						5,
					},
				},
				Workout{
					Name: "Bridges",
					Sets: []int{
						3,
						5,
					},
				},
				Workout{
					Name: "Neck work",
					Sets: []int{
						2,
						4,
					},
				},
			},
		},
	},
	"Supermax": Plan{
		Name: "Supermax",
		Days: Days{
			"Friday": []Workout{
				Workout{
					Name: "Pushups",
					Sets: []int{
						10,
						50,
					},
				},
				Workout{
					Name: "Leg Raises",
					Sets: []int{
						10,
						50,
					},
				},
			},
			"Monday": []Workout{
				Workout{
					Name: "Pullups",
					Sets: []int{
						10,
						50,
					},
				},
				Workout{
					Name: "Squats",
					Sets: []int{
						10,
						50,
					},
				},
			},
			"Saturday": []Workout{
				Workout{
					Name: "Handstand Pushups",
					Sets: []int{
						10,
						50,
					},
				},
				Workout{
					Name: "Bridges",
					Sets: []int{
						10,
						50,
					},
				},
			},
			"Sunday": []Workout{
			},
			"Thursday": []Workout{
				Workout{
					Name: "Pullups",
					Sets: []int{
						10,
						50,
					},
				},
				Workout{
					Name: "Squats",
					Sets: []int{
						10,
						50,
					},
				},
			},
			"Tuesday": []Workout{
				Workout{
					Name: "Pushups",
					Sets: []int{
						10,
						50,
					},
				},
				Workout{
					Name: "Leg Raises",
					Sets: []int{
						10,
						50,
					},
				},
			},
			"Wednesday": []Workout{
				Workout{
					Name: "Handstand Pushups",
					Sets: []int{
						10,
						50,
					},
				},
				Workout{
					Name: "Bridges",
					Sets: []int{
						10,
						50,
					},
				},
			},
		},
	},
	"Veterano": Plan{
		Name: "Veterano",
		Days: Days{
			"Friday": []Workout{
				Workout{
					Name: "Squats",
					Sets: []int{
						2,
						3,
					},
				},
			},
			"Monday": []Workout{
				Workout{
					Name: "Pullups",
					Sets: []int{
						2,
						3,
					},
				},
			},
			"Saturday": []Workout{
				Workout{
					Name: "Pushups",
					Sets: []int{
						2,
						3,
					},
				},
			},
			"Sunday": []Workout{
			},
			"Thursday": []Workout{
				Workout{
					Name: "Leg Raises",
					Sets: []int{
						2,
						3,
					},
				},
			},
			"Tuesday": []Workout{
				Workout{
					Name: "Bridges",
					Sets: []int{
						2,
						3,
					},
				},
			},
			"Wednesday": []Workout{
				Workout{
					Name: "Handstand Pushups",
					Sets: []int{
						2,
						3,
					},
				},
			},
		},
	},
}
//*/
